### ISSUE TITLE
Add Warning for Unsupported Browsers

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-front-end#128]
**Is your feature request related to a problem? Please describe.**

We currently don't support browsers older than IE 11.  We haven't heard from users that it's a problem, but it's hypothetically possible that someone would try to navigate to the site using IE 10 or before **and** not have access to a more modern browser or make the realization it's a browser support issue.

**Describe the solution you'd like**

If a user visits the site with an older unsupported browser, they should receive a pop up warning them, giving them a link or code@gsa.gov to request support for their browser (if they feel passionately about it), and recommend they try with a more modern browser.

**Describe alternatives you've considered**

Not sure

**Additional context**

It's difficult to support browsers before IE 11 because even the polyfills (scripts that provide modern functionality to old browsers) use objects and syntax that are too new for IE 10 and before (e.g. `const` and `Set`)

**Comment by ftonato** [comment]
Hi @DanielJDufour,

I don't know about project's rules, but i suggest don't use "pop up", it's likable and against best practices recommended (_UX_ design concepts).

I drew a simple page using project's style, you can see below:

![browser-not-supported](https://user-images.githubusercontent.com/5417662/51210397-9d3e8b80-190a-11e9-9438-eee54f1ef093.PNG)

**Comment by neilmartis** [comment]
@DanielJDufour  @saracope  @jcastle using React-Device detect we can detect the browser the user is using and accordingly redirect him-> npm package -> https://www.npmjs.com/package/detect-browser
https://www.npmjs.com/package/react-device-detect. Instead of puuting it on the UI side it will automatically detect it at runtime and change.

**Comment by DanielJDufour** [comment]
Hi, @neilmartis . Thanks for your willingness to take on this challenge :-)

I have some questions in return:
- How will the browser detection libraries be loaded?
- If you include them in the webpack bundle, how will the detection code execute if the bundle has "syntax errors" and doesn't run on an old browser.
- If you use a script tag, does the detection code run on IE10 and before?

Thanks again and let me know if I can be of assistance.  Have a great rest of the week and weekend!

**Comment by GrooveCS** [comment]
Is this still an open issue?

**Comment by neilmartis** [comment]
@GrooveCS Its an open issue but planning to complete it soon.

**Comment by GrooveCS** [comment]
Can we offer any support?

**Comment by jcastle** [comment]
Thanks to @neilmartis, @GrooveCS, and @DanielJDufour. Hoping to see a solution soon as we could use the support. Cheers!

**Comment by jcastle** [comment]
@neilmartis, had any time to work on this? If not, maybe @GrooveCS can help. I am looking to remove stale issues and PRs from the platform but don't want to close if this is going to be completed soon. Appreciate the help!

**Comment by neilmartis** [comment]
Sorry sir I didn't have any time working on it. I think Sarah has worked
part of it solution. Only need think which needs to be done is update index
file with IE tags and package json under the browser compatibility section

**Comment by jcastle** [comment]
Thanks @neilmartis! I conferred with @saracope and think we should close this issue since hardly any of our sites/platforms support much older than IE11 or comparable at this point. And, I haven't received a complaint on this. 

Due to our budget and priorities, we are facing resource constraints and prefer to focus on items that fit our current [Roadmap](https://code.gov/roadmap).

This said, I will close for now but definitely welcome PRs to review for a future fix from anyone in the community. Thanks to those who contributed to this issue and our platform as a whole.
