### ISSUE TITLE
`Visit Repo` button display

### ISSUE THREAD

**Issue by saracope** [GSA/code-gov-front-end#164]
The `Visit Repo` button should not display if the repoURL is null.

See [ITARS](https://code.gov/projects/va_oit_epmo_2_information_technology_acquisition_request_system) project.

<img width="1246" alt="Screen Shot 2019-03-21 at 2 48 53 PM" src="https://user-images.githubusercontent.com/2197515/54777348-80635480-4be8-11e9-807e-64164ed50a59.png">

**Comment by RicardoAReyes** [comment]
I like this enhance.

**Comment by ftonato** [comment]
Hi @saracope,

Is this a `bug`?

Our code always check the `repositoryUrl`, but the problem here is because the API returns **"null"** as `String`.

We can check this out on _src/utils/repo-parsing.js_:

```js
// file: src/utils/repo-parsing.js

export function parseRepositoryURL(repo) {
  let url = get(repo, 'repositoryURL')
  if (Boolean(url)) {
    // code ...
  }
}
```

I think its not frontend responsibility validate if the repository URL is valid, the backend needs ensure this.

The frontend don't know how to validate this. We can validate `"null"` but probably this problem will ocurrence again when the saved value was `"undefined"` or whatever `"string"`.

My suggestion is "the backend needs to guarantee the saved value" and if it's invalid, set it to null...

**Comment by afomi** [comment]
@saracope, please let me know if you have any questions about https://github.com/GSA/code-gov-front-end/pull/353 👋

**Comment by jcastle** [comment]
Completed with PRs #388 & #353
