### ISSUE TITLE
Update search results text

### ISSUE THREAD

**Issue by saracope** [GSA/code-gov-front-end#216]
**Describe the bug**

**To Reproduce**
1. Go to https://code.gov/
2. Click on the home page search box
3. Enter GSA and hit return
4. See error: only 100 results are returned

**Expected behavior**

A search for GSA on the home page should return the same number of results (or more) as selecting the agency GSA from the filters on Browse Projects.

**Screenshots**

**Additional context**

<img width="540" alt="Screen Shot 2019-06-03 at 7 07 19 AM" src="https://user-images.githubusercontent.com/2197515/58797561-578b1280-85ce-11e9-8002-814ae898c97a.png">
<img width="675" alt="Screen Shot 2019-06-03 at 7 07 11 AM" src="https://user-images.githubusercontent.com/2197515/58797562-578b1280-85ce-11e9-8229-b287aec15191.png">

**Comment by ftonato** [comment]
Hello,

I'm trying to reproduce this behaviour following the steps but I didn't able.

![error](https://user-images.githubusercontent.com/5417662/58863571-f422e280-86aa-11e9-932d-951e94e4de6d.gif)

**Comment by saracope** [comment]
Thanks for testing. I updated the description. The issue is that those 2 search boxes are the same component. If you click on General Services Administration from the Federal Agency dropdown, you get a much larger number of projects. The search boxes should return at least that many projects when searching for GSA.

If you search for other items like API or design, you'll see that the search only returns 100 items as a limit.

**Comment by DanielJDufour** [comment]
Hi, @saracope and @ftonato .  I wanted to provide some more context into why I set 100 as the maximum amount of search results and perhaps suggest some options for improvement.  The search results page automatically generates the filter box options based on scanning all of the returned repos.  This requires loading up all of the repos into the browser.  100 was selected to limit the size of data we try to transfer over the network.  For example, if we tried to load and process all 2056 repos returned by searching for 'GSA', it would take approximately 20x as long for the search results to load!

One solution to this issue would be to update the /repos api, so that it returns the options for the filter boxes (sets of agencies, languages, licenses, etc.), so we don't have to load all the repos to get the filter options.

Hope this helps and let me know if you have any more questions :-)

**Comment by saracope** [comment]
Thanks, @DanielJDufour. Makes sense. 

In the mean time, we could change the text to say 'Top 100 repos' or something like that to help inform on what's getting returned.

**Comment by saracope** [comment]
Updating the title of this issue.  Requested change would be to change the search results text to `Top 100 repositories for...`

Example:
<img width="831" alt="Screen Shot 2019-10-01 at 9 37 40 AM" src="https://user-images.githubusercontent.com/2197515/65967151-24974500-e42f-11e9-97bf-1e82dceb9654.png">
