### ISSUE TITLE
Metadata validator for code.json?

### ISSUE THREAD

**Issue by lbeaufort** [GSA/code-gov-front-end#504]
Hi there! I'm working on regenerating FEC's code.json and I can't seem to find a metadata validator. This is something that used to be here: https://code.gov/#/policy-guide/docs/compliance/inventory-code/tools/validate-schema but I can't find anything on code.gov.

I'd like to make sure I haven't somehow broken our formatting before uploading changes, so a validator would be helpful. Please let me know if the validator lives somewhere else now, or if I'm on my own. 

Thanks!

**Comment by jcastle** [comment]
Thanks @lbeaufort! Moved over to the code-gov-front-end for long-term traceability. We plan to bring back the validator at some point but removed because it wasn't working with our latest Schema 2.0. 

We were using [NPM jsoneditor](https://www.npmjs.com/package/jsoneditor). But any generic json validator will work for checking the file. Unfortunately, none of them will validate to the schema.
