### ISSUE TITLE
Code.gov.X: open-source project for sharing X's code

### ISSUE THREAD

**Issue by gtabidze** [GSA/code-gov-front-end#92]
**Is your feature request related to a problem? Please describe.**
Current IA, UI only presents data, but the way we present data to users is also important. 

**Describe the solution you'd like**
We have to reimagine UI and IA. [The brief](https://wetransfer.com/downloads/14a42cd0f7588f5417a51b40becf725b20181121192456/3972db)

**Describe alternatives you've considered**
Why not build open-source web project for any code.gov.X  to expand code.gov mission?

**Additional context**
Assume project have a product design guy, who knows AZ of how to design and execute SaaS products.

**Comment by DanielJDufour** [comment]
Hi, @gtabidze .  I'd love to talk to you about your ideas on contributing to the project.  Could you email me at daniel.dufour@gsa.gov?  As a start, the content and some options of the project are configurable through our [site.json](https://github.com/GSA/code-gov-front-end/blob/master/config/site/site.json).  Our backend is also open-source and can be reused.  Regarding the UX, we have specific requirements on what code.gov looks like given to us by our product owner and UX lead, so it's not something that we, as developers, have control over.  That said, we are trying to make code-gov-front-end and our style guide reusable, so I would recommend forking this repo and our [style guide](https://github.com/GSA/code-gov-style) and coming up with a version better for your situation.  Even if we don't use your suggestions for styling (because of specific requirements we have), there may be people from around the world who would love to use your ideas!

I'm closing this issue for now because we mainly use the Github issues for bug tracking and specific feature requests.  If you have any ideas about specific parts of the site, I'd encourage you to create an issue for each one.  Here's the guidelines for your reference: https://github.com/GSA/code-gov-front-end/blob/master/CONTRIBUTING.md#issue-guidelines

I also apologize for not having the CONTRIBUTING.md up sooner.  We are in the middle of updating the documentation for this repo.

Best,
Daniel
