### ISSUE TITLE
Add name of the Project to Open Tasks

### ISSUE THREAD

**Issue by AABoyles** [GSA/code-gov-front-end#98]
**Is your feature request related to a problem? Please describe.**

When I visit [Open Tasks](https://code.gov/open-tasks?page=1&size=10), the issues listed often make sense _in the context of the project_, but the issue titles aren't sufficiently context-revealing without the project title. For example, let's look at [this issue](https://github.com/nasa/openmct/issues/1879) from the Open Tasks. The title is "Y Axis disappears when deeply zoomed". This tells us that the project with the issue involves a plot of some sort, but not a lot more. We can infer additional information from the Agency (NASA), but this becomes less useful as agencies begin to index multiple projects. Suppose that in addition to OpenMCT (the project from which that issue comes), NASA also started indexing issues from another repo with visualizations, like [EarthData-Search](https://github.com/nasa/earthdata-search). Suddenly, the above issue could refer to either project, and I couldn't determine which without clicking on the issue link.

**Describe the solution you'd like**

I propose that each card on the open tasks view also include the name of project from which it was scraped. More specifically, I'd like to see "**Project**:" or "**Repository**:" placed inline before "**Agency**" in each card.

**Comment by DanielJDufour** [comment]
Hi, @AABoyles . Thank you for your detailed description of the issue.  I'm tagging our UI/UX lead who might have some thoughts on this.

**Comment by DanielJDufour** [comment]
Hi, @AABoyles , turns out that we already had a design for this and I had missed that.  Our team thinking is waiting for the Open Tasks API Endpoint to be created on the backend and then we can programmatically grab the repo name, rather than manually adding to all the tasks in a static JSON file.  Here's our Mockup.  

![05_help_wanted_color_usability_updates](https://user-images.githubusercontent.com/4313463/49097233-59000a80-f23a-11e8-8825-a83f14a58611.png)
 
Would this address your issue?

**Comment by AABoyles** [comment]
Wow, that's _exactly_ what I had in mind! Can't wait to see it in prod!
